<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ComfyTyped</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup Condition="Exists('../../../SwarmUI.csproj')">
    <ProjectReference Include="../../../SwarmUI.csproj">
      <Private>false</Private>
      <Properties>_EnableMacOSCodeSign=false;StaticWebAssetsEnabled=false</Properties>
      <GlobalPropertiesToRemove>BaseIntermediateOutputPath;TargetName</GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
